[Feat] `GET /my-page/bookmarks` 커서 페이징 추가
team-ecolink/map2zero-backend pull request #100
Opened 2024-02-13 01:07 UTC by uuujini

## 📌 관련 이슈
-#60 

## ✨ PR 내용
- `GET /my-page/bookmarks` 커서 페이징 추가

## 📚 레퍼런스 혹은 궁금한 사항들
- 기존 `feature/bookmark-api` 브랜치에 이슈가 있어서 새로 브랜치 생성 후 작업했습니다! 
- 북마크 리스트 커서 페이징을 최대한 해보았는데 보완할 점이 많은 거 같아서 피드백 주시면 감사하겠습니다! 

## 📸 스크린샷(선택)

2024-02-13 06:48 UTC, heegane requested changes

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
> +			.limit(pageSize + 1L);
`request` 안에 size가 있으니까 `request.getSize()` 를 써주세요!!

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
> +	public List<MyPageBookmarkResponse> findBookmarkedStores(MyPageBookmarkRequest request, Long lastBookmarkId, int pageSize, Long avatarId) {
`request` 안에 `cusor`랑 `size`가 있으니까 `lastBookmarkId`, `pageSize`는 없어도 될 것 같아요~

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
> +		boolean authenticated = avatarId != null;
`avatarId`가 null일 경우는 없기 때문에 해당 코드는 없어도 될 것 같습니다!!

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
> +				authenticated ? bookmark.isNotNull() : Expressions.FALSE))
여기도 `authenticated` 없어도 되겠네용

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
> +				storePhoto,
`MyPageBookmarkResponse` 인자가 `Store`, `ImageFile`인 것 같던데, 그러면 `storePhoto.getFile`이 들어가야 되겠네용

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
> +			.orderBy(store.bookmarkCnt.desc(), store.id.desc())
기획 상 정렬 기준은 북마크 id 최신순이여서 `bookmarkCnt.desc()`는 없어도 될 것 같습니다~! 그리고 `store.id.desc()`를 `bookmark.id.desc()`로 바꿔주면 되겠네용

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
> +		if (authenticated) {
`authenticated`가 false일 수는 없으니까 if절 빼면 됩니다! 그 아래 로직은 굿굿

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkListService.java
> +	public CursorPage<MyPageBookmarkResponse, Long> getByStoreAndAvatar(MyPageBookmarkRequest request, Pageable pageable, Long avatarId) {
커서 페이지라서 `pageable`은 없어도 돼요!

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/avatar/dto/response/MyPageBookmarkResponse.java
> +	@Schema(description = "매장 홍보 멘트", example = "에코 상점은 환경을 위한 다양한 제품을 판매합니다.")
기획 보니까 내가 북마크한 상점 리스트 조회 기능에는 홍보 멘트가 필요 없는 것 같네요~

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/avatar/controller/MyPageController.java
> +		Pageable pageable) {
여기두 커서 페이징이기 때문에 pageable 없어도 됩니다

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
> +			query.where(store.id.lt(lastBookmarkId));
커서가 `bookmarkId` 기준이면, `store.id.lt(lastBookmarkId)`가 아니라 `bookmark.id.lt(lastBookmarkId)` 이어야 되겠네요~!!

2024-02-13 06:48 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
> +			query.leftJoin(bookmark)
`leftJoin` 이 아니라 `join(inner join)`으로 바꿔야 되겠네요! 그래야 `avatar`와 `bookmark`의 교집합(=내가 북마크 한 ~~)이 반환 되겠네요~!

2024-02-14 01:52 UTC, uuujini commented on src/main/java/com/ecolink/core/avatar/dto/response/MyPageBookmarkResponse.java
> +	@Schema(description = "매장 홍보 멘트", example = "에코 상점은 환경을 위한 다양한 제품을 판매합니다.")
홈 화면에서 보이는 북마크에서도 `MyPageBookmarkResponse` 사용하기 위해서 홍보 멘트 필드 추가해뒀습니다!!

2024-02-14 12:52 UTC, wnsvy607 requested changes

2024-02-14 12:52 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +		return bookmarkRepository.existsByAvatarAndStore(storeId, avatarId);
이 부분 순서가 바뀐것 같아요!

2024-02-14 12:52 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/repository/BookmarkJpaRepository.java
cursor를 확인하는 where문이 빠졌네요!

2024-02-14 14:43 UTC, heegane requested changes

2024-02-14 14:43 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +	public Bookmark addBookmark(Long storeId, Long avatarId) {
매개변수 순서를 바꾸면서 관련된 컨트롤러가 작동이 잘 되지 않고 있어요~ `BookmarkController`에 `addBookmark`, `deleteBookmark` 등을 확인해주세요!!

2024-02-15 00:11 UTC, wnsvy607 approved these changes
LGTM 👍

2024-02-15 00:11 UTC, merged