[FEAT] `매장 검색 결과 조회 API` 추가
team-ecolink/map2zero-backend pull request #30
Opened 2024-01-20 10:54 UTC by heegane

## 📌 관련 이슈
- #20 

## ✨ PR 내용
- `searchStores` 서비스 로직
    - 메인 로직
    - type이 매장일 때
        - `Store` 객체를 조회
            - `Store` 조회 기준/조건 : 
                - 매장명에 keyword가 포함되면서 bookmark 수를 기준으로 내림차순으로 정렬, bookmark 수가 동일하다면 매장명의 가나다 순으로 정렬
        - `Store`를 순회하면서 `Store`에 해당하는 product 최대 3개 조회
            - `StoreProduct` 검색 기준/조건 : 
                - 제품명의 가나다 순으로 정렬
        - `mainPhotoUrl`, `isBookmarked` 조회
        - Dto 반환  

    - type이 제품일 때
        - `Store` 객체를 조회
            - `Store` 조회 기준/조건 : 
                - `StoreProduct`의 Product.name에 keyword가 포함되면서 `Store`의 bookmark 수를 기준으로 내림차순 정렬, bookmark 수가 동일하다면 매장명의 가나다 순으로 정렬
        - `Store`를 순회하면서 `Store`에 해당하는 product 최대 3개 조회
            - `StoreProduct` 검색 기준/조건 : 
                - StoreProduct의 첫 번째 product는 keyword를 포함한 StoreProduct로 위치시킴(firstProduct), 나머지 두 개의 제품은 firstProduct를 제외한 제품명의 가나다 순으로 정렬
        - `mainPhotoUrl`, `isBookmarked` 조회
        - Dto 반환
    - 부가 로직
        - `SearchHistory` 저장 

## 📚 레퍼런스 혹은 궁금한 사항들
전반적으로 미숙한데 피드백 주시면 반영하겠습니다!
특히 Cursor Pagination 부분 확인해 주시면 감사하겠습니다!

## 📸 스크린샷(선택)

2024-01-25 11:24 UTC, wnsvy607 requested changes

2024-01-25 11:24 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +	public Boolean isBookmarked(Avatar avatar, Store store) {
`return avatar != null && bookmarkRepository.existsBookmarkByAvatarIdAndStoreId(avatar.getId(), store.getId());`
로 줄인다면 더 간결해질 것 같아요!

2024-01-25 11:24 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/dto/response/StoreSearchDto.java
> +	private final String photoUrl;
`ImageFile` 사용부탁드립니다!

2024-01-25 11:24 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/event/SaveSearchHistoryEvent.java
> +public class SaveSearchHistoryEvent extends ApplicationEvent {
`ApplicationEvent` 상속 받지 않아도 됩니다!

2024-01-27 08:16 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/event/StoreSearchEvent.java
GOOD 👍

2024-01-27 09:23 UTC, wnsvy607 requested changes
- Event 부분 피드백 반영된거 확인했습니다! 
- 디테일한 부분 수정이 필요해 보입니다!

2024-01-27 09:23 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
이 부분 확인 부탁해요~!

2024-01-27 09:23 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/dto/response/StoreSearchDto.java
> +		this.totalScore = store.getTotalScore();
`totalScore` 가 모든 리뷰 점수의 합을 캐싱해 놓는 컬럼이라 그대로 표시하는 것보다
(리뷰 총점 / 리뷰 개수) 작업을 통해서 리뷰 점수 평균을 보여주는게 좋을 것 같아요!
(리뷰 총점 / 리뷰 개수)를 반환하는 메서드를 `Store` 엔티티에 선언해서 쓰면 좋겠네요!
그리고 변수명도 `totalScore` 보단 `score` 나 `averageScore` (평균 점수라는 의미로) 바꾸는게 좋겠어요!

2024-01-27 09:23 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/repository/StoreJpaRepository.java
> +		if (id == null) {
해당 메서드는 id != null 일때 호출되는거라 없어도 될것 같아요!

2024-01-27 09:23 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/domain/Store.java
> +	private List<StoreProduct> storeProducts;
`= new ArrayList<>()`;
를 추가하는게 좋아요!

2024-01-27 09:23 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/service/StoreProductService.java
> +	public void getTop3StoreProducts(StoreSearchRequest request, List<StoreSearchDto> storeSearchDtos) {
해당 메서드의 리턴타입이 `void`라서 메서드 이름에 `get`이 들어가는건
적절하지 않은것 같아요!

2024-01-27 09:55 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
해당 서비스 더 이상 사용하지 않아서 삭제했습니다~!

2024-01-27 11:30 UTC, wnsvy607 approved these changes
LGTM 👍

2024-01-27 11:34 UTC, merged