[FEAT] `POST/{storeId}/bookmarks` API 추가
team-ecolink/map2zero-backend pull request #31
Opened 2024-01-21 07:28 UTC by uuujini

## 📌 관련 이슈
- #23 

## ✨ PR 내용
- 매장별 상세 화면에서 북마크 등록하는 POST/{storeId}/bookmarks API 추가

## 📚 레퍼런스 혹은 궁금한 사항들
- 매장 상세 페이지별 하나의 북마크
- 북마크를 등록하는 사용자

이렇게 기준을 두고 코드를 작성해 보았는데, 
고민이 되는 부분이 있습니다! 

예를 들어, 
매장별 상세페이지 화면에 북마크가 존재하니
bookmark가 아닌 store 쪽에 controller를 두어야 하는가.. 고민을 하였으나 bookmarkController로 두었습니다!

피드백 주시면 감사하겠습니다!!

## 📸 스크린샷(선택)

2024-01-25 03:25 UTC, wnsvy607 requested changes

2024-01-25 03:25 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/controller/BookmarkController.java
> +		@RequestParam Long avatarId,
`avatarId` 를 파라미터로 받지 않고
`UserPrincipal` 에서 `getAvatarId()`를 호출하면 avatarId를 받아올 수 있습니다!

2024-01-25 03:25 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/controller/BookmarkController.java
- `@PathVariable` 대신 `@RequestBody`로 Body를 받아오는게 어떤가요? 
기존 명세에 `PathVariable`은 따로 입력하지 않도록 되어있습니다!
- 그리고 북마크는 앞에 stores를 안 붙인 `api/v1/bookmarks`로 설정하는건 어떤가요?

2024-01-25 03:25 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +	public boolean existsBookmark(Avatar avatar, Store store) {
해당 메서드도 (Long avatarId, Long storeId) 이렇게 받도록 바꿔야 할 것 같아요!

2024-01-25 03:25 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +		if (!existsBookmark(avatar, store)) {
```java
if (existsBookmark(avatar, store)) {
    throw new 커스텀예외(ErrorCode.커스텀 코드)
}
{기존 로직}
return BookmarkResponse.of(savedBookmark);
```
1. 북마크가 존재할 경우 예외임을 클라이언트에게 알리는게 좋을 것 같아요! (+ `GeneralException`을 상속하는 커스텀 예외, `ErrorCode`에 커스텀 코드 추가해서 쓰기)
2. 기존 로직 순서를 위처럼 검증 -> 북마크 저장 으로 바꾸는게 가독성에 더 좋을것 같아요!

2024-01-25 03:25 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +	public BookmarkResponse addBookmark(Long avatarId, Long storeId) {
`INSERT, UPDATE`가 있기 때문에 `@Transactional` 붙여야 합니다!

2024-01-25 03:25 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +	public BookmarkService(BookmarkRepository bookmarkRepository, AvatarService avatarService, StoreService storeService) {
별다른 이유가 없다면 `@RequiredArgsConstructor` 쓰는게 좋을것 같아요!

2024-01-25 03:25 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/service/StoreService.java
> +	public StoreService(StoreRepository storeRepository) {
이 부분도 `@RequiredArgsConstructor` 쓰는게 어때요?

2024-01-25 12:54 UTC, uuujini commented on src/main/java/com/ecolink/core/bookmark/controller/BookmarkController.java
상세하게 피드백 주셔서 감사합니다!
피드백 주신 내용 참고하여 수정해 보았는데,

`BookmarkController`에서 `@RequestBody`를 사용하면 Request를 받아와야 하는 거 같아 `@RequestParam`으로 대체하였는데 확인 한 번만 더 부탁드리겠습니다!
지난 회의 때 Request Dto는 현재 기능에서 안 써도 될 거 같다고 하셔서 `@PathVariable` 대신 `@RequestParam`을 사용해 보았습니다!

2024-01-25 17:48 UTC, wnsvy607 reviewed
Controller 관련 conversation만 해결되면 될것 같아요!
나머지 고생하셨습니다 👍👍

2024-01-25 17:48 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/controller/BookmarkController.java
http 메서드가 `GET`이 아닌 경우 왠만하면 `@RequestBody`를 쓰기로 했던 것으로 기억하는데 제가 그랬었나요!? 제 생각엔 메서드가 `GET`이 아니라면 쿼리 파라미터(`@RequestParam`)는 불필요한 것 같아요! 제가 잘못말했나봐요 ㅠ

2024-01-26 13:16 UTC, uuujini commented on src/main/java/com/ecolink/core/bookmark/controller/BookmarkController.java
넵 감사합니다! 
`GET`이 아닌 경우 `@RequestBody` 기억하겠습니다!!

2024-01-27 08:04 UTC, wnsvy607 approved these changes
고생했습니다! 👍

2024-01-27 08:09 UTC, merged