[Feat] `GET /stores/{id}` 매장 상세 페이지 API 추가
team-ecolink/map2zero-backend pull request #32
Opened 2024-01-21 11:31 UTC by cherryiJuice

## 📌 관련 이슈

- #27 

## ✨ PR 내용

- 매장 기본 정보, 판매 중인 제품, 리뷰, 이벤트 조회 가능
- 기획에서 리뷰에 태그가 추가되어 `ReviewTag` Entity 추가
- 인증을 선택적으로 하여 `USER` 권한을 가진 사용자만 리뷰 좋아요 여부 확인 가능
- 북마크 관련은 유진님이 하고 계셔서 따로 처리하지 않음 -> 나중에 처리 예정
- 현재는 인증 여부를 주석처리 -> 나중에 처리 예정

## 📚 레퍼런스 혹은 궁금한 사항들

- 리뷰 페이지네이션과 동적 쿼리가 필요한지 궁금

## 📸 스크린샷(선택)

2024-01-25 12:31 UTC, wnsvy607 requested changes

2024-01-25 12:31 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/controller/StoreController.java
> +	@Operation(summary = "매장 상세 페이지 API", description = "매장 상세 페이지 - 인증 선택",
summary에 '- 인증 선택' 붙여주세요~

2024-01-25 12:31 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/controller/StoreController.java
> +		// if(userPrincipal.getAuthorities().contains(new SimpleGrantedAuthority(RoleType.USER.getAuthority()))){
`AuthorityUtil`라는 유틸 클래스를 지금 PR에 올렸으니 해당 PR 머지되면 develop 브랜치로 리베이스해서 
`AuthorityUtil.hasAutority` 메서드로 검증하면 될 겉 같아요~

2024-01-25 12:31 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/domain/Store.java
`cascade` 와 `orphanRemoval` 은 의도치 않은 레코드 삭제를 유도하는 위험한 옵션이기 때문에
`@OneToMany`를 사용할 때는 필요한 곳에만 적용할 필요가 있습니다~
지금 단순 조회 메서드이기 때문에 필요한 부분은 없어보여서 모두 빼주시면 감사하겠습니다!

2024-01-25 12:31 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/domain/StoreProduct.java
> +	private Integer price;
피드백 반영된 부분 좋아요!

2024-01-25 12:31 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/dto/AddressDto.java
`Address`는 엔티티가 아니라 값 타입이기 때문에
`AddressDto`를 따로 만들 필요 없고 `Address` 그대로 써도 됩니다!

2024-01-25 12:31 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/dto/StorePhotoDto.java
포맷 통일을 위해 해당 Dto 대신 `List<ImageFile>`을 사용하면 될것 같아요~

2024-01-25 12:31 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/service/StoreSearchService.java
`fetch join` 으로 쿼리가 나가는 횟수를 최소화 할 수 있을 것 같아요
`StoreRepository`에 ID를 기준으로 
fetch join을 적용해 매장관련 엔티티를 함께 조회하는 메서드를 만들어 보세요~

2024-01-26 07:06 UTC, wnsvy607 requested changes

2024-01-26 07:06 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/repository/StoreRepository.java
> +		+ "where s.id = :id")
`StorePhoto`, `StoreOperatingHour` `fetch join` 잘했습니다.
그런데 추가로 `StoreTag` 와 `Tag`도 할 필요가 있어 보이네요

2024-01-26 07:14 UTC, cherryiJuice commented on src/main/java/com/ecolink/core/store/repository/StoreRepository.java
> +		+ "where s.id = :id")
오 맞다

2024-01-26 07:32 UTC, wnsvy607 requested changes
직접 API 호출을 해보니 `MultipleBagFetchException` 가 발생하네요~
`fetch join` 대상에 `OneToMany`가 2개 이상 있을 때 발생하는 에러입니다
제가 해당 사항을 간과하고 있었네요
우선 쿼리 최소화를 위해 `StoreTag`, `Tag` 두 가지만 `fetch join` 하면 될 것 같아요
그리고 `Store`가 `StoreTag`가 없을 수도 있기 때문에 `left` 키워드 추가로 붙여야 합니다~

그리고 `StoreDetailResponse`에 score 항목이 누락되어 있습니다! 
매장의 점수를 계산하는 메서드를 `Store`에 추가한 뒤 해당 Dto에서 사용해주시기 바랍니다~

2024-01-26 08:06 UTC, wnsvy607 requested changes

2024-01-26 08:06 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/dto/OperatingHourDto.java
> +	DayOfWeek dayOfWeek,
이렇게 하면 응답값이 `MON` , `SUN` 이런식으로 enum type의 이름이 나갑니다~
String 타입으로 변환한뒤 `DayOfWeek.getName`의 리턴 값을 넣어주세요!

2024-01-28 09:33 UTC, wnsvy607 approved these changes
LGTM 👍

2024-01-28 17:42 UTC, merged