[Feat] `GET /stores/{storeId}/reviews` 리뷰 리스트 조회 API
team-ecolink/map2zero-backend pull request #35
Opened 2024-01-24 09:47 UTC by cherryiJuice

## 📌 관련 이슈

- #27 

## ✨ PR 내용

- 페이지네이션 적용

## 📚 레퍼런스 혹은 궁금한 사항들

## 📸 스크린샷(선택)

2024-01-29 07:11 UTC, cherryiJuice reviewed
수고하셨습니다👏

2024-01-29 13:39 UTC, wnsvy607 requested changes
현재 코드에 크게 2가지 문제가 있습니다
1. JPA에서 컬렉션 fetch join과 페이징을 동시에 하면 서버 메모리에서 페이징을 하게 되고 서버 성능에 심각한 영향을 줄수 있습니다. OneToMany에 대한 fetch join을 제외해주세요~
 2. `reviewLikeService.isLiked(review, avatar)` 이 부분에서 쿼리가 조회한 리뷰의 개수만큼나가게 됩니다. 쿼리 한번에 조회할 수 있도록 개선 바랍니다~!

2024-01-29 13:39 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/domain/Review.java
> +	@BatchSize(size = 100)
이 어노테이션 안써도 기본으로 배치 처리됩니다

2024-01-29 13:39 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/dto/response/ReviewResponse.java
> +	LocalDate createdAt,
혹시 `LocalDate`로 변환한 이유가 있나요?
그리고 변수명 통일을 위해 `createdDate` 로 수정바랍니다~

2024-01-29 13:39 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/service/ReviewSearchService.java
> +		Pageable pageable = PageRequest.of(request.getPageNo(), request.getSize(), Sort.by(Sort.Direction.DESC, request.getCriteria()));
컨트롤러에서 Pageable 직접 받을 수 있어서 그거 쓰면 될것 같네요~

2024-01-29 13:39 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/repository/ReviewRepository.java
> +		+ "left join r.reviewPhotos "
이 부분에 fetch 없는 left join은 어떤 이유로 한건가요?

2024-01-29 13:39 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/service/ReviewSearchService.java
> +		return reviewService.getByAvatar(review, avatar);
직접 쿼리할 필요 없이 
`return review.getWriter().getId().equals(avatar.getId());`
하면됩니다.

2024-01-29 13:39 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/repository/ReviewRepository.java
> +		+ "where s.id=:storeId")
등호 앞뒤로 띄어쓰기 해주세요

2024-01-29 13:39 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/service/ReviewSearchService.java
> +	public List<ReviewResponse> getByStore(Long storeId, Long avatarId, ReviewSearchRequest request) {
리턴타입 Page<>로 바꿔주시고
`ApiPageResponse<>` 클래스 만들어서 PR할테니 거기에 넣어서 써주세요~

2024-01-29 15:23 UTC, cherryiJuice commented on src/main/java/com/ecolink/core/review/dto/response/ReviewResponse.java
> +	LocalDate createdAt,
나온 화면을 봤을 때 시각까지 나와 있지 않아서요! 
그리고 createdDate로 고치겠습니다

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/like/repository/ReviewLikeRepository.java
> +										 @Param("avatarId") Long avatarId);
정렬이 잘못된거 같아요

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/like/repository/ReviewLikeRepository.java
> +		+ "where r.id in :reviewIds "
join할 필요가 없습니다~
where l.avatar.id = ~~ and l.review.id in ~~
이렇게 바꿔주세요

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/like/service/ReviewLikeService.java
> +		List<Long> reviewIds = reviewLikes.stream().map(reviewLike ->
`List` 대신 `Set`을 쓴다면 더 빨라요

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/like/service/ReviewLikeService.java
> +		reviews.forEach(getReviewResponse -> {
이것보다
stream().filter().forEach()를 사용하는게 직관적일 것 같네요~

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/repository/StoreRepository.java
> +import com.ecolink.core.bookmark.domain.Bookmark;
이거 안쓰는 건데 추가되어있네요

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/dto/response/GetReviewResponse.java
> +	public GetReviewResponse setLiked(boolean isLikedParam) {
리턴값 안쓰여서 제거해도 될 것 같네요

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/repository/ReviewRepository.java
> +										 @Param("avatarId") Long avatarId,
여기도 정렬 이상하네요

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/dto/response/GetReviewResponse.java
> +	public static GetReviewResponse of(Review review, boolean isLiked, boolean isWriter) {
boolean isLiked 여기 이 매개변수는 항상 false라서 아예 지워도 무방할 것 같네요

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/service/ReviewSearchService.java
> +		Avatar avatar = avatarService.getById(avatarId);
`Avatar`는 존재하는게 보장이 되므로 따로 쿼리 한번 더 날릴 이유가 없습니다~

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/repository/ReviewRepository.java
> +		+ "join fetch r.store s "
store는 왜 join fetch를 했나요?

2024-01-31 09:44 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/repository/ReviewRepository.java
> +			"join fetch r.store s " +
이 부분도요

2024-01-31 09:58 UTC, cherryiJuice commented on src/main/java/com/ecolink/core/like/service/ReviewLikeService.java
> +		List<Long> reviewIds = reviewLikes.stream().map(reviewLike ->
`reviewLikeRepository.findAllByReviewList` 얘 반환값도 Set으로 하나요?

2024-01-31 10:00 UTC, cherryiJuice commented on src/main/java/com/ecolink/core/like/service/ReviewLikeService.java
> +		reviews.forEach(getReviewResponse -> {
어떻게?

2024-01-31 10:27 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/like/service/ReviewLikeService.java
> +		List<Long> reviewIds = reviewLikes.stream().map(reviewLike ->
그건 안바꿔도 돼요~

2024-01-31 10:33 UTC, cherryiJuice commented on src/main/java/com/ecolink/core/like/service/ReviewLikeService.java
> +		List<Long> reviewIds = reviewLikes.stream().map(reviewLike ->
```
Set<ReviewLike> reviewLikes = reviewLikeRepository.findAllByReviewList(
			reviews.map(GetReviewResponse::getId).toList(), avatarId).stream().collect(Collectors.toSet());

Set<Long> reviewIds = reviewLikes.stream().map(reviewLike ->
				reviewLike.getReview().getId()).collect(Collectors.toSet());
```
이렇게만 바꿔?

2024-02-01 14:27 UTC, wnsvy607 approved these changes

2024-02-01 14:27 UTC, merged