[Feat] Delete /bookmarks API 추가
team-ecolink/map2zero-backend pull request #43
Opened 2024-01-28 11:46 UTC by uuujini

## 📌 관련 이슈
- #23

## ✨ PR 내용
- 북마크 취소 API 추가

## 📚 레퍼런스 혹은 궁금한 사항들

## 📸 스크린샷(선택)

2024-01-29 00:42 UTC, heegane requested changes

2024-01-29 00:42 UTC, heegane commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +		if (!existsBookmark(avatarId, storeId)) {
해당 방법도 좋지만 `avatarId`와 `storeId`에 해당하는 `Bookmark` 객체를 리턴하는 메서드를 서비스 레이어에 만들고,
리턴한 객체를 `bookmarkRepository.delete(bookmark)`를 통해서 삭제하는 방법은 어떨까요~?
그렇게 수정하면 코드의 재사용성이 더 좋아질 것 같다는 의견입니다!

2024-01-29 06:19 UTC, uuujini commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +		if (!existsBookmark(avatarId, storeId)) {
감사합니다! 
알려주신 방법대로 수정해 볼게요!!

2024-01-29 13:58 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/controller/BookmarkController.java
> +	public ResponseEntity<?> deleteBookmark(
ㅋㅋㅋㅋ ?은 왜썼어요

2024-01-29 13:58 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +		if (!existsBookmark(avatarId, storeId)) {
현희님이 말씀하신 방법이 좋을 것 같아요!

2024-01-29 13:58 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/store/domain/Store.java
> +	public void deleteBookmarkCount() {
북마크 개수가 0 또는 음수인 경우 에러를 반환하도록
```java
if(this.bookmarkCnt <= 0)
throw new IllegalStateException("에러 메세지");
```
아래와 같이 수정한다면 좋을 것 같아요!

2024-01-30 23:34 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/bookmark/service/BookmarkService.java
> +		Store store = bookmark.getStore();
해당 메서드에서 쿼리가 총 2번 나가게 되는데요, `fetch join` 을 사용하면 쿼리를 1번으로 줄일 수 있을 것 같아요

2024-01-30 23:38 UTC, wnsvy607 reviewed
- 피드백 반영된 것 확인 했습니다 👍

2024-01-31 02:23 UTC, heegane approved these changes
LGTM👍

2024-01-31 05:31 UTC, merged