[Feat] `POST /reviews` API 추가
team-ecolink/map2zero-backend pull request #76
Opened 2024-02-05 05:51 UTC by heegane

## 📌 관련 이슈
- #66 

## ✨ PR 내용
- 리뷰 쓰기 API 추가

## 📚 레퍼런스 혹은 궁금한 사항들

## 📸 스크린샷(선택)

2024-02-05 15:18 UTC, cherryiJuice requested changes

2024-02-05 15:18 UTC, cherryiJuice commented on src/main/java/com/ecolink/core/review/dto/request/CreateReviewRequest.java
> +@Builder
`builder` 때문에 테스트 할 때 에러나는 거 같아요

2024-02-06 06:52 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/service/ReviewCreateService.java
> +		if (tags != null) {
이 부분은 46번째 라인과 합칠 수 있을 것 같아요~

2024-02-06 06:52 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/review/dto/response/GetReviewResponse.java
일부러 필드 이름 바꾼건데 충돌 해결 과정에서 바뀐것 같아요~!

2024-02-06 09:21 UTC, wnsvy607 approved these changes
LGTM 👍

2024-02-06 09:24 UTC, cherryiJuice approved these changes
LGTM

2024-02-06 09:24 UTC, merged