[Feat] `GET /products/today` API 추가
team-ecolink/map2zero-backend pull request #93
Opened 2024-02-09 06:15 UTC by heegane

## 📌 관련 이슈
- #91 

## ✨ PR 내용
- 오늘의 제로웨이스트 상품 조회 API

## 📚 레퍼런스 혹은 궁금한 사항들

## 📸 스크린샷(선택)

2024-02-11 10:56 UTC, cherryiJuice commented on src/main/java/com/ecolink/core/product_recommend/controller/ProductRecommendController.java
> +	@Tag(name = "${swagger.tag.store}")
홈화면 페이지 하나 만들어도 좋을 거 같아요

2024-02-11 10:56 UTC, cherryiJuice commented on src/main/java/com/ecolink/core/product_recommend/repository/ProductRecommendRepository.java
> +	List<StoreProduct> findStoreProductsWithPhotosByRecommendType(@Param("type") RecommendType type);
패치조인으로 연관 엔티티 가져와서`ProductRecommend` 반환하면 쿼리 한 번에 처리 가능하지 않을까요?

2024-02-11 23:46 UTC, wnsvy607 requested changes

2024-02-11 23:46 UTC, wnsvy607 commented on src/main/resources/application-swagger.yml
요즘 뜨는 매장 조회 API에서 태그가 `store`로 되어 있던데 `home`으로 수정해주세요~

2024-02-11 23:46 UTC, wnsvy607 commented on src/main/java/com/ecolink/core/product_recommend/repository/ProductRecommendRepository.java
- 실제로 사용되는 객체가 `ProductRecommend `가 아닌 `StoreProduct`인 점
- join fetch로 쿼리 수를 줄일 수 있다는 점
두 가지를 고려했을 때 다음과 같이 변경하면 좋을것 같네요~
```java
	@Query("select sp "
		   + "from StoreProduct sp "
		   + "join fetch ProductRecommend pr "
		   + "on pr.storeProduct = sp "
		   + "join fetch sp.photos "
		   + "join fetch sp.product "
		   + "join fetch sp.store "
		   + "where pr.type = :type ")
	List<StoreProduct> findStoresByType(@Param("type") RecommendType type);
```
리턴 타입도 `StoreProduct`로 변하니까 Service도 그에 맞게 간단하게 변경해주면 될 것같네요

2024-02-12 02:38 UTC, cherryiJuice approved these changes
수고하셨습니다👍

2024-02-12 02:50 UTC, wnsvy607 approved these changes
LGTM 👍

2024-02-12 02:50 UTC, merged